app/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[Assert\NotNull(groups: ['edit'])]
    #[Assert\Length(min: 3, max: 50, groups: ['edit'])]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $first_name = null;

    #[Assert\Length(min: 3, max: 32, groups: ['edit'])]
    #[ORM\Column(length: 32, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo_url = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $status = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Advertisement::class)]
    private Collection $advertisements;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ExchangeOffers::class)]
    private Collection $exchangeOffers;

    #[Assert\NotNull(groups: ['edit'])]
    #[Assert\Length(min: 3, max: 50, groups: ['edit'])]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $last_name = null;

    #[Assert\NotNull(groups: ['edit'])]
    #[Assert\Length(min: 11, max: 15, groups: ['edit'])]
    #[ORM\Column(length: 20, nullable: true)]
    private ?string $phone = null;

    #[Assert\Email(groups: ['edit'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $auth_date = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_edit = null;

    public function __construct()
    {
        $this->advertisements = new ArrayCollection();
        $this->exchangeOffers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): User
    {
        $this->id = $id;
        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): User
    {
        $this->first_name = $first_name;
        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username ?? "#{$this->getId()}";
    }

    public function setUsername(?string $username): User
    {
        $this->username = $username;
        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photo_url;
    }

    public function setPhotoUrl(?string $photo_url): User
    {
        $this->photo_url = $photo_url;
        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(?int $status): User
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return Collection<int, Advertisement>
     */
    public function getAdvertisements(): Collection
    {
        return $this->advertisements;
    }

    public function addAdvertisement(Advertisement $advertisement): static
    {
        if (!$this->advertisements->contains($advertisement)) {
            $this->advertisements->add($advertisement);
            $advertisement->setUser($this);
        }

        return $this;
    }

    public function removeAdvertisement(Advertisement $advertisement): static
    {
        if ($this->advertisements->removeElement($advertisement)) {
            // set the owning side to null (unless already changed)
            if ($advertisement->getUser() === $this) {
                $advertisement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ExchangeOffers>
     */
    public function getExchangeOffers(): Collection
    {
        return $this->exchangeOffers;
    }

    public function addExchangeOffser(ExchangeOffers $exchangeOffser): static
    {
        if (!$this->exchangeOffers->contains($exchangeOffser)) {
            $this->exchangeOffers->add($exchangeOffser);
            $exchangeOffser->setUser($this);
        }

        return $this;
    }

    public function removeExchangeOffser(ExchangeOffers $exchangeOffser): static
    {
        if ($this->exchangeOffers->removeElement($exchangeOffser)) {
            // set the owning side to null (unless already changed)
            if ($exchangeOffser->getUser() === $this) {
                $exchangeOffser->setUser(null);
            }
        }

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAuthDate(): ?int
    {
        return $this->auth_date;
    }

    public function setAuthDate(int $auth_date): static
    {
        $this->auth_date = $auth_date;

        return $this;
    }

    public function getRoles(): array
    {
        return [];
    }

    public function eraseCredentials(): void
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return $this->username ?? $this->getId();
    }

    public function isIsEdit(): ?bool
    {
        return $this->is_edit;
    }

    public function setIsEdit(?bool $is_edit): static
    {
        $this->is_edit = $is_edit;

        return $this;
    }
}

app/templates/commons/footer.html.twig
{{ include('components/_full-banner.html.twig', {banners: {page: {full_banner: banners.all.bottom ?? null}}}) }}

<footer class="footer-area footer-area-2 footer-area-5 pt-30 ">
    <div class="footer-bottom pt-25">
        <div class="container">
            <div class="copyright d-inline-block ">
                <p>©CopyRight 2024 by <a href="https://t.me/noxcho_inc" target="_blank">Bubaev</a>. Все права зашищены.</p>
            </div>
            <div class="payment-card float-right">
            </div>
        </div>
    </div>
</footer>

app/templates/commons/header.html.twig
<header>
    <div class="header-area header-3 header-5 ">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="header-top">
                        <div class="header-top-left d-inline-block pb-10 pb-sm-0">
                            <ul class="user-info d-flex pt-15">
                                <li><a href="{{ path('app_account') }}">{% trans %}site.account.my_account{% endtrans %}</a></li>
                            </ul>
                        </div>
                        <div class="header-top-right float-right pt-15 d-flex justify-content-end">
                            <ul class="language d-flex ">
                                <li>
                                    <a href="/chr" class="{% if lang == 'chr' %}lang-active{% endif %}">
                                        <img src="{{ asset('img/icon/noxchi.png') }}" alt=""> Нохчи
                                    </a>
                                </li>
                                <li>
                                    <a href="/" class="{% if lang == 'ru' %}lang-active{% endif %}">
                                        <img src="{{ asset('img/icon/russia.png') }}" alt=""> Русский
                                    </a>
                                </li>
                            </ul>
{#                            <ul class="mony">#}
{#                                <li><a href="#"><i class="fas fa-dollar-sign"></i> USD</a>#}
{#                                    <ul class="sub-mony">#}
{#                                        <li><a href="#"><i class="fas fa-euro-sign"></i>ERO</a></li>#}
{#                                        <li><a href="#"><i class="fas fa-yen-sign"></i>CNY</a></li> #}
{#                                    </ul>#}
{#                                </li>#}
{#                            </ul>#}
                        </div>
                    </div>
                </div>

            </div>
            <hr class="pt-10">
            <div class="header-menu mt-15 pt-5 pb-25">
                <div class="row">
                    <div class="col-xl-3 col-lg-2 col-md-2 col-sm-3 col-5 order-sm-1 offset-xl-0 offset-lg-0 offset-md-4 offset-sm-4 ">
                        <div class="logo text-center text-lg-left">
                            <a href="{{ path('app_index') }}" class="logo">
                                <span>H</span>ica
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-8  order-2 d-none d-lg-block">
                        <div class="main-menu pt-5">
                            <nav id="mobile-menu">
                                <ul>
                                    <li>
                                        <a href="{{ path('app_index') }}">Главная</a>
                                    </li>
                                    <li>
                                        <a href="{{ path('app_advertisement') }}">Обменник</a>
                                    </li>
                                    <li><a href="{{ path('app_news') }}">Новости</a></li>
                                    <li><a href="{{ path('page', {page: 'contacts'}) }}">Контакты</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-md-6 col-sm-4 col-7 order-sm-3">
                        <div class="d-flex justify-content-end">
                            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                                <div class="user-auth-block">
                                    <div class="user-auth-info">
                                        {% if app.user.photoUrl is not empty %}
                                            <img src="{{ app.user.photoUrl }}" class="rounded-circle w-35">
                                        {% endif %}
                                        <span class="font-weight-bold link-opacity-100">{{ app.user.username }}</span>
                                    </div>

                                    <ul class="user-auth-sub-menu">
                                        <li><a href="{{ path('app_account') }}">Аккаунт</a></li>
                                        <li><a href="{{ path('app_my_advertisements') }}">Мои объявления</a></li>
                                        <li><a href="blog-detalis-page.html">Настройки</a></li>
                                        <li><a href="blog-left-sidebar-page.html">Уведомления <span class="badge">21</span></a></li>
                                        <li><a href="{{ path('app_logout') }}">Выход</a></li>
                                    </ul>
                                </div>
                            {% else %}
                                {{
                                    render(controller('App\\Controller\\TelegramLoginController::widget', {
                                        telegramBotName: telegram_bot_name
                                    }))
                                }}
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>
            <div class="mobile-menu"></div>
        </div>
    </div>
</header>