app/src/Entity/Advertisement.php
<?php

namespace App\Entity;

use App\Repository\AdvertisementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: AdvertisementRepository::class)]
class Advertisement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'advertisements')]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Gedmo\Slug(fields: ['name'])]
    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $seo_keywords = null;

    #[ORM\Column(length: 512)]
    private ?string $seo_description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $text = null;

    #[ORM\Column(nullable: true)]
    private ?int $price = null;

    #[ORM\Column(length: 512)]
    private ?string $exchange_for_what = null;

    #[ORM\OneToMany(mappedBy: 'advertisement', targetEntity: AdvertisementImages::class)]
    #[ORM\OrderBy(['base' => 'DESC'])]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'advertisement', targetEntity: ExchangeOffers::class)]
    private Collection $offers;

    #[ORM\OneToMany(mappedBy: 'proposed_advertisement', targetEntity: ExchangeOffers::class)]
    private Collection $proposedAdvertisement;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $status = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->offers = new ArrayCollection();
        $this->proposedAdvertisement = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSeoKeywords(): ?string
    {
        return $this->seo_keywords;
    }

    public function setSeoKeywords(?string $seo_keywords): static
    {
        $this->seo_keywords = $seo_keywords;

        return $this;
    }

    public function getSeoDescription(): ?string
    {
        return $this->seo_description;
    }

    public function setSeoDescription(string $seo_description): static
    {
        $this->seo_description = $seo_description;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getExchangeForWhat(): ?string
    {
        return $this->exchange_for_what;
    }

    public function setExchangeForWhat(string $exchange_for_what): static
    {
        $this->exchange_for_what = $exchange_for_what;

        return $this;
    }

    /**
     * @return Collection<int, AdvertisementImages>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addAdvertisementImage(AdvertisementImages $advertisementImage): static
    {
        if (!$this->images->contains($advertisementImage)) {
            $this->images->add($advertisementImage);
            $advertisementImage->setAdvertisement($this);
        }

        return $this;
    }

    public function removeAdvertisementImage(AdvertisementImages $advertisementImage): static
    {
        if ($this->images->removeElement($advertisementImage)) {
            // set the owning side to null (unless already changed)
            if ($advertisementImage->getAdvertisement() === $this) {
                $advertisementImage->setAdvertisement(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ExchangeOffers>
     */
    public function getOffers(): Collection
    {
        return $this->offers;
    }

    public function addExchangeOffser(ExchangeOffers $exchangeOffser): static
    {
        if (!$this->offers->contains($exchangeOffser)) {
            $this->offers->add($exchangeOffser);
            $exchangeOffser->setAdvertisement($this);
        }

        return $this;
    }

    public function removeExchangeOffser(ExchangeOffers $exchangeOffser): static
    {
        if ($this->offers->removeElement($exchangeOffser)) {
            // set the owning side to null (unless already changed)
            if ($exchangeOffser->getAdvertisement() === $this) {
                $exchangeOffser->setAdvertisement(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ExchangeOffers>
     */
    public function getProposedAdvertisement(): Collection
    {
        return $this->proposedAdvertisement;
    }

    public function addMyExchangeOffser(ExchangeOffers $myExchangeOffser): static
    {
        if (!$this->proposedAdvertisement->contains($myExchangeOffser)) {
            $this->proposedAdvertisement->add($myExchangeOffser);
            $myExchangeOffser->setProposedAdvertisement($this);
        }

        return $this;
    }

    public function removeMyExchangeOffser(ExchangeOffers $myExchangeOffser): static
    {
        if ($this->proposedAdvertisement->removeElement($myExchangeOffser)) {
            // set the owning side to null (unless already changed)
            if ($myExchangeOffser->getProposedAdvertisement() === $this) {
                $myExchangeOffser->setProposedAdvertisement(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }
}

app/src/Controller/AdvertisementController.php
<?php

namespace App\Controller;

use App\Service\AdvertisementService;
use App\Service\RandomAdvertisementsService;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdvertisementController extends BaseController
{
    #[Route('/advertisements', name: 'app_advertisement')]
    public function index(AdvertisementService $advertisementService): Response
    {
        return $this->render('advertisement/index.html.twig', [
            'pagination' => $advertisementService->getAdvertisement(),
        ]);
    }

    #[Route('/advertisement/{slug}', name: 'app_advertisement_details')]
    public function details(string $slug, AdvertisementService $advertisementService) : Response
    {
        $details = $advertisementService->getAdvertisementDetails($slug);
        $offers = $advertisementService->getAdvertisementOffers($details->getId());

        return $this->render('advertisement/details.html.twig', [
            'details' => $details,
            'offers' => $offers
        ]);
    }

    public function randAdvertisements(RandomAdvertisementsService $service): Response
    {
        return $this->render('advertisement/random-advertisements.html.twig', [
            'advertisements' => $service->advertisements()
        ]);
    }
}

app/templates/advertisement/details.html.twig
{% extends 'base.html.twig' %}

{%
    set breadcrumbs = [
        {title: 'Объявления', link: path('app_advertisement')},
        {'title' : meta.seo_title ?? details.name}
    ]
%}

{% block title %}{{ details.name }}{% endblock %}
{% block description %}{{ details.name }}{% endblock %}

{% block body %}

    <div class="product-area product-shop-page  product-list-page product-detalis-page mt-50">
        <div class="container">

            <div class="row">
                <div class="col-xl-5 col-lg-7 col-md-6 col-sm-12">
                    <div class="product-list-slider">
                        {% for item in details.images %}
                            <div class="product-img">
                                <img src="{{ asset(item.image) }}" alt="">
                            </div>
                        {% endfor %}
                    </div>
                    <div class=" slider-nav-thumbnails product-list-active">
                        {% for item in details.images %}
                            <a {% if item.base %}class="active"{% endif %}>
                                <img src="{{ asset(item.image) }}" alt="">
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-xl-7 col-lg-5 col-md-6 col-sm-12">
                    <div class="product-wrapper product-wrapper-2">
                        <div class="product-detalis">
{#                            {{ include('advertisement/components/seller.html.twig') }}#}

                            <div class="product-interested pb-20">
                                <b>Обмен на:</b>
                                {{ details.exchangeForWhat }}
                            </div>

                            <div class="product-interested">
                                <b>Описание:</b> {{ details.text }}
                            </div>

                            {% if details.price %}
                                <div class="price d-inline-block pt-25">
                                    Цена: <span>{{ details.price|price }}</span>
                                </div>
                            {% endif %}

                            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                                {% if details.user.id != app.user.id %}
                                    {% if app.user is not null and  app.user.phone is null %}
                                        <p class="rounded-3px bg-danger text-white p-3 my-5">
                                            Чтобы у вас была возможность откликнуться на объявления, Вам необходимо заполнить
                                            номер телефона и имя пользователя в <a href="{{ path('app_account') }}" class="text-bold text-dark">аккаунте</a>
                                        </p>
                                    {% else %}
                                        <div class="cart-view my-5">
                                            <div {{ react_component('ProposeExchange', {advertisementId: details.id}) }}>
                                                Загрузка ... <i class="fas fa-cog fa-spin fa-2x"></i>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% else %}
                                    <p class="text-center pt-2">
                                        Вы являетесь владельцем данного объявления.
                                    </p>
                                {% endif %}

                            {% else %}
                                <div class="rounded-3px bg-danger text-white p-3 my-5">Чтобы предложить обмен нужно авторизоваться</div>
                            {% endif %}

                            {% if offers is not empty %}
                                {{ include('advertisement/components/proposed.html.twig') }}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{ render(controller('App\\Controller\\AdvertisementController::randAdvertisements')) }}

{% endblock %}

app/templates/advertisement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ meta.seo_title ?? 'site.advertisement'|trans }}{% endblock %}

{%
    set breadcrumbs = [
        {'title' : block('title')}
    ]
%}

{% block body %}

    <div class="product-area product-area-3 pt-45 ">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="section-title">
                        <h3>
                            Объявления
                        </h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="container pl-0 pr-0">
            <div class="custom-row row">
                {% for item in pagination %}
                    {{ include ('components/advertising-item.html.twig') }}
                {% endfor %}

                {{ include ('components/pagination.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/advertisement/random-advertisements.html.twig
<div class="product-area pt-50 ">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="section-title">
                    <h3>
                        Случайные объявления
                    </h3>
                </div>
            </div>
        </div>
        <hr>
    </div>
    <div class="container pl-0 pr-0">
        <div class="custom-row ">
            <div class="product-active pt-30">
                {% for item in advertisements %}
                    {{ include ('components/advertising-item.html.twig') }}
                {% endfor %}
            </div>
        </div>
    </div>
</div>