app/src/Entity/Banner.php
<?php

namespace App\Entity;

use App\Repository\BannerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BannerRepository::class)]
class Banner
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sub_title = null;

    #[ORM\Column(length: 512, nullable: true)]
    private ?string $text = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $button_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $button_link = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $css_class = null;

    #[ORM\Column(length: 20)]
    private ?string $block = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $visible = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 15)]
    private ?string $section = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSubTitle(): ?string
    {
        return $this->sub_title;
    }

    public function setSubTitle(?string $sub_title): static
    {
        $this->sub_title = $sub_title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getButtonName(): ?string
    {
        return $this->button_name;
    }

    public function setButtonName(?string $button_name): static
    {
        $this->button_name = $button_name;

        return $this;
    }

    public function getButtonLink(): ?string
    {
        return $this->button_link;
    }

    public function setButtonLink(?string $button_link): static
    {
        $this->button_link = $button_link;

        return $this;
    }

    public function getCssClass(): ?string
    {
        return $this->css_class;
    }

    public function setCssClass(?string $css_class): static
    {
        $this->css_class = $css_class;

        return $this;
    }

    public function getBlock(): ?string
    {
        return $this->block;
    }

    public function setBlock(string $block): static
    {
        $this->block = $block;

        return $this;
    }

    public function getVisible(): ?int
    {
        return $this->visible;
    }

    public function setVisible(?int $visible): static
    {
        $this->visible = $visible;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getSection(): ?string
    {
        return $this->section;
    }

    public function setSection(string $section): static
    {
        $this->section = $section;

        return $this;
    }
}

app/templates/index/components/_deal-area.html.twig
<div class="deal-area deal-area-4 deal-area-5 deal-height position-relative pb-50 mt-50" style="background-image: url(https://html.themexplosion.com/moly/assets/img/product/product-bg-11.png);">
    <div class="container">

        <div class="row">
            <div class="col-xl-6 col-lg-8 col-md-9 col-sm-12 offset-xl-1 offset-lg-1 offset-md-1 ">
                <div class="time-area">

                    <h2>Men T-Shirt Fashion <span>- 2019</span></h2>
                    <span class="pr-30">Phasellus vel elit efficitur, gravida libero sit amet, scelerisque mauris.</span>
                    <a href="shop-detalis-page.html" class="d-inline-block pl-20"> <i class="fa fa-plus" aria-hidden="true"></i> Discover Now________</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/index/components/_last-news.html.twig
<div class="blog-area blog-area-4">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="section-title  ">
                    <h3 class="pb-5">
                        Последние новости
                    </h3>
                    <hr>
                </div>
            </div>
        </div>

    </div>
    <div class="container pl-0 pr-0">
        <div class="custom-row">
            <div class=" blog-active-4 pt-30">

                {{ render(controller('App\\Controller\\NewsController::lastNewsFromIndexPage')) }}

            </div>
        </div>
    </div>
</div>

app/templates/index/components/_product-banner.html.twig
<div class="product-banner-area pt-50">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-5 col-md-6 col-sm-6 col-12">
                <div class="banner-wrapper position-relative">
                    <div class="banner-img">
                        <img src="https://html.themexplosion.com/moly/assets/img/product/product-36.png" alt="women">
                    </div>
                    <div class="banner-content  pt-30 pl-55">
                        <h5>Women Smart Shirt</h5>
                        <a href="shop-detalis-page.html"><i class="fa fa-plus" aria-hidden="true"></i>Discover More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-lg-5 col-md-6 col-sm-6 col-12 offset-xl-2 offset-lg-2">
                <div class="banner-wrapper banner-padding position-relative">
                    <div class="banner-img">
                        <img src="https://html.themexplosion.com/moly/assets/img/product/product-34.png" alt="women">
                    </div>
                    <div class="banner-content  pt-30 pl-55">
                        <h5>Women Smart Shirt</h5>
                        <a href="shop-detalis-page.html"><i class="fa fa-plus" aria-hidden="true"></i>Discover More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-lg-5 col-md-6 col-sm-6 col-12">
                <div class="banner-wrapper mt-50 position-relative">
                    <div class="banner-img">
                        <img src="https://html.themexplosion.com/moly/assets/img/product/product-35.png" alt="women">
                    </div>
                    <div class="banner-content  pt-30 pl-55">
                        <h5>Women Smart Shirt</h5>
                        <a href="shop-detalis-page.html"><i class="fa fa-plus" aria-hidden="true"></i>Discover More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12 offset-xl-1 offset-lg-1">
                <div class="hot-sale-product-area pt-160">
                    <div class=" hot-lookbook">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="col-xl-12">
                                    <div class="section-title pb-10">
                                        <h3>
                                            On-Sale Product
                                        </h3>
                                    </div>
                                    <hr>
                                </div>
                            </div>
                        </div>
                        <div class="custom-row">
                            <div class=" hot-sale-product-active-3 pt-30">
                                <div class="col-xl-6">
                                    <div class="product-wrapper d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-23.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-wrapper mt-25 d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-27.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis ">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="product-wrapper d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-24.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-wrapper mt-25 d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-28.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis ">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="product-wrapper d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-21.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-wrapper mt-25 d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-25.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis ">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="product-wrapper d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-22.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-wrapper mt-25 d-flex">
                                        <div class="product-img pr-15">
                                            <img src="https://html.themexplosion.com/moly/assets/img/product/product-26.png" alt="product">
                                            <div class="cart-icon">
                                                <img src="https://html.themexplosion.com/moly/assets/img/icon/cart-white.png" alt="cart">
                                            </div>
                                        </div>
                                        <div class="product-detalis ">
                                            <span>Men Dress</span>
                                            <h6><a href="shop-detalis-page.html">Military Patch Pocket Blazer</a></h6>
                                            <div class="price d-flex">
                                                <span>$999</span>
                                                <del>$899</del>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/index/components/_slider.html.twig
{% set banners = banners.page.slider ?? null %}

{% if banners is defined %}

    <div class="slider-area slider-area-5  owl-carousel position-relative">

        {% for banner in banners %}
            <div class="single-slide pb-45" style="background-image: url({{ banner.image }});">
                <div class="slider-content slider-height pt-60">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-7 col-md-9 col-sm-9 col-12 offset-xl-0 offset-lg-1 offset-md-1 offset-sm-1">
                                <div class="hero-text pt-120">
                                    {% if banner.title is not empty %}
                                        <h1 class="pr-130 pb-10">
                                            {{ banner.title }}
                                        </h1>
                                    {% endif %}

                                    {% if banner.text is not empty %}
                                        <p>{{ banner.text }}</p>
                                    {% endif %}

                                    {% if banner.buttonName is not empty %}
                                        <a href="{{ banner.buttonLink }}"><i class="fa fa-plus" aria-hidden="true"></i>
                                            {{ banner.buttonName }}
                                        </a>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

{% endif %}